language: node_js
node_js:
  - "stable"
before_script:
  - npm install
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE mydiary;' -U postgres
script:
  - npm test
after_script:
  - npm run coverage
notifications:
  email: false
sudo: false
